### ISSUE TITLE
Suggest khard as an alternative in README

### ISSUE THREAD

**Issue by owenh000** [libvc/rolo#2]
There hasn't been a lot of activity for rolo, as was also mentioned in this [comment](https://github.com/libvc/rolo/issues/1#issuecomment-325110120). A possible alternative is [khard](https://github.com/scheibler/khard); it can also read vCard files directly and may be of interest to some people.

It might be helpful to mention this on the README? I can open a pull request for that if it would be helpful.

**Comment by rlaboiss** [comment]
Thanks for drawing my attention to khard.  I was not aware of this project. I decided to resurrected the libvc/rolo project (I am not the original author) only because I have not found any alternatives to them.

Sure, submit a pull request, please.
